.github/workflows/build-and-push.yml
.github/workflows/unit-test.yml

Both workflows for PRs and pushes were cleaned up. On a push (which includes when PRs merge), the code base is linted and tested first before building and publishing.

chore: Update GH Action workflows

---

.tekton/listener.yaml
.tekton/pipeline.yaml
.tekton/task.yaml
scripts/deploy/iks/build-image-dind.sh
scripts/deploy/iks/deploy-mm-serving.sh

Update docker push script to use the latest commit time to
determine whether to push a new image to Docker Hub.
No need to push a new image to Docker Hub for the "latest" tag if there is no changes
Add logic to script to use the latest  commit time to determine whether to publish
A new image is pushed to the "latest" tag only if a change is made

Update docker push

---

.github/workflows/build-and-push.yml
.github/workflows/lint.yml
.github/workflows/run-fvt.yml

Updated unit-test and docs workflows to not run on a PR with only doc changes. Also made linting a separate action.
Fixes: https://github.com/kserve/modelmesh-serving/issues/14

Update workflows to be more selective

---

docs/predictors/README.md

correct the broken links
setup-storage.md  -> storage.md
run-inference.md -> inferencing.md

correct the broken links in readme

---

docs/install/install-script.md
scripts/delete.sh

remove changes to the cluster when importing a namespace

---

docs/trainedmodel.md

Fix broken links in readme
Updated docs
Linking to the correct document.

Fix broken links in trainedmodel.md

---

docs/install/environment.md

Signed-off-by: ted chang <htchang@us.ibm.com>
Fix broken links in the environment.md

fix broken links in environment.md

---

.gitignore
.pre-commit-config.yaml

```
➜  modelmesh-serving git:(remove-trainedmodel) ✗ pre-commit run --all-files
[INFO] Installing environment for https://github.com/prettier/prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/pugang/.cache/pre-commit/repomcthnonm/node_env-default/bin/node', '/Users/pugang/.cache/pre-commit/repomcthnonm/node_env-default/bin/npm', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: …
```

fix prettier error

---

controllers/config.go
controllers/modelmesh/cluster_config.go
controllers/modelmesh/modelmesh.go
controllers/predictor_controller.go
controllers/service_controller.go
controllers/servingruntime_controller.go
fvt/helpers.go
fvt/predictor_test.go
pkg/mmesh/modelmesh_events.go
pkg/mmesh/modelmesh_service.go

This reverts commit 60a7b4468c4c3433812ca787d5790cd14bb59167.
It was inadvertenly squash-merged when we intended to merge the commits individually.

Revert "Sync internal changes (#69)"

---

controllers/config.go
controllers/modelmesh/cluster_config.go
controllers/modelmesh/modelmesh.go
controllers/predictor_controller.go
controllers/service_controller.go
controllers/servingruntime_controller.go
fvt/helpers.go
fvt/predictor_test.go
pkg/mmesh/modelmesh_events.go
pkg/mmesh/modelmesh_service.go

This is a replay of https://github.com/kserve/modelmesh-serving/pull/69 which was inadvertently squashed rather than merged as individual commits.
**Reminder:** Don't `\lgtm` this PR, we'll `Rebase and merge` when ready

Sync internal changes take 2

---

config/certmanager/certificate.yaml

Same as https://github.com/kserve/kserve/commit/df512fdf943303fb21d9fd8d3aaff818c5705851

config: upgrade the cert manager resource version

---

config/crd/patches/cainjection_in_predictors.yaml
config/crd/patches/cainjection_in_servingruntimes.yaml
config/crd/patches/webhook_in_predictors.yaml
config/crd/patches/webhook_in_servingruntimes.yaml
config/default/webhookcainjection_patch.yaml
config/rbac/auth_proxy_client_clusterrole.yaml

https://kubernetes.io/docs/reference/using-api/deprecation-guide/

Config: Upgrade the K8s APIs to v1

---

controllers/predictor_controller.go

Small follow-up to https://github.com/kserve/modelmesh-serving/pull/83. Initially I was thinking that we'd pass a JSON struct through under `StorageParams`, but, after consideration, decided that we should just pass through the parameters from the Predictor's `storage.parameters` field as-is without any transformation.
[These changes](https://github.com/kserve/modelmesh-runtime-adapter/pull/12) in the puller parse a `map[string]string`  from the storage parameters, so the two sides of the communication match up for runtimes using the puller.
- refactor `StorageParams` to be a `map[string]string` instead of `map[string]interface{}`
- remove unneeded `tranformParameters` (sic 😅 ) function

refactor: be explicit in StorageParams having string values only

---

config/example-predictors/example-keras-mnist-predictor.yaml
config/runtimes/triton-2.x.yaml
controllers/testdata/servingruntime_controller.golden
docs/model-types/README.md
docs/model-types/keras.md

Update Keras doc and examples to reflect the changes in the updated minio images

Update Keras model example and docs

---

scripts/install.sh

Signed-off-by: ted chang <htchang@us.ibm.com>
Fix #113

Fix install script failure on OSX 12

---

scripts/delete.sh
scripts/deploy/iks/deploy-mm-serving.sh
scripts/install.sh

Fix install issues for user namespaces on Mac
Fix mac os install issues
Use sed i.bak
User can install in mac os

Fix install issues for user namespaces on Mac

---

config/default/config-defaults.yaml
config/manager/kustomization.yaml
docs/component-versions.md
scripts/setup_user_namespaces.sh

This is for the v0.8.0 release.

[release-0.8] Update tags and refs

---

docs/component-versions.md
release/RELEASE_PROCESS.md
scripts/setup_user_namespaces.sh

Reflecting the latest release.
Also some release process items were updated.

chore: Update component versions in doc

---

config/default/config-defaults.yaml
config/rbac/modelmesh-service-account.yaml
config/rbac/service-account.yaml

Seems we missed some cleanup items in the open source transition.

chore: Clean up some internal-related snippets

---

config/default/config-defaults.yaml
config/rbac/modelmesh-service-account.yaml
config/rbac/role.yaml
config/rbac/service-account.yaml

Some minor config related cherry-picks to ensure release-0.8 branch works on OpenShift.

[release-0.8] Config cherry-picks

---

.github/workflows/run-fvt.yml
fvt/fvtclient.go
fvt/globals.go
fvt/helpers.go
fvt/isvc_test.go
fvt/testdata/isvcs/new-format-mm.yaml
fvt/testdata/isvcs/old-format-mm.yaml
fvt/utils.go

feat: FVT for inference service.

---

docs/README.md
docs/configuration/built-in-runtimes.md
docs/model-types/README.md
docs/model-types/openvino-ir.md

Signed-off-by: Angel Luu <angel.luu@us.ibm.com>
Update docs after the changes for OVMS and `openvino-ir` model support in #141 .

docs: Add docs for OpenVINO

---

README.md

Signed-off-by: Angel Luu <angel.luu@us.ibm.com>
I missed this top level README in previous doc PR (https://github.com/kserve/modelmesh-serving/pull/167)

docs: Update top level README

---

release/RELEASE_PROCESS.md

Added portion about updating quickstart.md doc.

docs: Update RELEASE_PROCESS doc

---

docs/component-versions.md
docs/install/install-script.md
scripts/setup_user_namespaces.sh

Update latest versions in various docs/scripts.

chore: update latest component versions

---

OWNERS

I would like to be able to selected from the list of "Reviewers" to help out with PR reviews.
Append `  - ckadner` under `reviewers:` in `OWNERS` file.
The list of reviewers gets one entry longer :-)
/cc @njhill

chore: Add myself as a reviewer

---

OWNERS

Add Rafael as a reviewer

---

docs/quickstart.md

Missed to update on doc in previous round.
Edit the `docs/quickstart.md` file, updating the `RELEASE` variable in the "Get the latest release" section to the new release branch name.
Correct version of release branch in Quickstart guide
/cc @njhill 
/assign @njhill

Update release version in quickstart.md

---

docs/component-versions.md
docs/install/install-script.md
scripts/setup_user_namespaces.sh

Follow release process step 5:
> 5. Update the following files in the `main` branch with the same versions as in the steps above, submit them in a PR to `main`, and wait for that PR to be merged:
> 
>     - [x] docs/component-versions.md
>     - [x] docs/quickstart.md
>     - [x] docs/install/install-script.md
>     - [x] scripts/setup_user_namespaces.sh
Updated version tags from `v0.10.0-rc0` to `v0.10.0`.
Docs reflect latest release (yet to be published)
---
/cc @njhill 
/assign @njhill

release: Update `main` docs for version `v0.10.0`

---

.github/workflows/fvt.yml

It can be helpful to run FVTs on the latest code base to compare run results with those of a current PR.
Update FVT workflow definition to run on `workflow_dispatch` event
TBD

test: Enable FVTs to be triggered manually

---

.tekton/task.yaml
scripts/deploy/iks/build-image-dind.sh

Update fvt toolchain

---

.github/workflows/build.yml
.github/workflows/codeql.yml
.github/workflows/fvt-base.yml
.github/workflows/lint.yml
.github/workflows/test.yml
scripts/deploy/iks/test-fvt.sh

https://github.com/kserve/modelmesh-serving/security
> **Code scanning configuration error**
> CodeQL is reporting errors. Check the [tool status](https://github.com/kserve/modelmesh-serving/security/code-scanning/tools/CodeQL/status/configurations/actions-FZTWS5DIOVRC653POJVWM3DPO5ZS6Y3PMRSXC3BOPFWWY/b3dc626bc1db336b4a359feba12ef6c0998163ba0ab6e63305c9bc82567d61c9) for help.
- update Go version for build/test/lint workflow(s)
- update versions of (all) GitHub actions
TBD

chore: update GitHub actions

---

docs/examples/python-custom-runtime/custom-model/requirements.txt

Updating packages used in recently introduced custom runtime example.
- https://github.com/kserve/modelmesh-serving/security/dependabot/14 
- https://github.com/kserve/modelmesh-serving/security/dependabot/15

chore: Update requirements in custom runtime example

---

Dockerfile
Dockerfile.develop

chore: Use latest ubi image tag

---

CODE_OF_CONDUCT.md
SECURITY.md

chore: Part of https://github.com/kserve/community/issues/42

add security.md
