kserve/modelmesh-serving

- .pre-commit-config.yaml
The .tekton and .github directories do not need linting.
> Exclude some directories from lint checks

- .github/workflows/run-fvt.yml
- fvt/predictor_test.go
- fvt/scale_to_zero_test.go
This is an attempt to get FVTs running on a per-PR basis which will be used for gating code changes.
A workflow is added to run the e2e tests on the Github Actions environment using Minikube. Some FVTs were adjusted to get them working on the new environment. 
A new FVT check through Github Actions.
Part of https://github.com/kserve/modelmesh-serving/issues/9
> fvt: Add Github Action for functional tests

- docs/predictors/README.md
In the `Updating the model` , we are want to updated model type using `tensorflow` instead of `sklearn` , also the model name format is not matched in the output message of `run inference` . Thanks 
Some debug snapshots:
**run inference:** 
```
% grpcurl -plaintext -proto fvt/proto/kfs_inference_v2.proto -d '{ "model_name": "example-mnist-predictor", "inputs": [{ "name": "predict", "shape": [1, 64], "datatype": "FP32", "contents": { "fp32_contents": [0.0, 0.0, 1.0, 11.0, 14.0, 15.0, 3.0, 0.0, 0.0, 1.0, 13.0, 16.0, 12.0, 16.0, 8.0, 0.0, 0.0, 8.0, 16.0, 4.0, 6.0, 16.0, 5.0, 0.0, 0.0, 5.0, 15.0, 11.0, 13.0, 14.0, 0.0, 0.0, 0.0, 0.0, 2.0, 12.0, 16.0, 13.0, 0.0, 0.0, 0.0, 0.0, 0.0, 13.0, 16.0, 16.0, 6.0, 0.0, 0.0, 0.0, 0.0, 16.0, 16.0, 16.0, 7.0, 0.0, 0.0, 0.0, 0.0, 11.0, 13.0, 12.0, 1.0, 0.0] …
```
> correct the output messages

- Dockerfile.develop
The old link does not seem to work anymore.
> Update kubebuilder link in Dockerfile.develop

- .github/workflows/run-fvt.yml
- fvt/fvtclient_test.go
Decrease the flakiness of FVT runs that occur when certain tests are run back to back.
The rollingUpdate strategy is adjusted in a preprocessing step of the FVT Github Actions workflow to allow better stability in low resource environments. The defaultTimeout was increased to account for the the changes in strategy. Ran into some intermittent failures due to timeouts when the deployment doesn't become ready in time.
Less flakiness in FVT runs.
> Adjust FVT GH-Actions workflow

- config/runtimes/triton-2.x.yaml
- controllers/testdata/servingruntime_controller.golden
Errors were observed by @tedhtchang in this situation:
```
chmod: changing permissions of '/models/_triton_models/simple-string-1180__ksp-a53a19561f/config.pbtxt': Operation not permitted
chmod: changing permissions of '/models/_triton_models/simple-string-167__ksp-a53a19561f': Operation not permitted
chmod: changing permissions of '/models/_triton_models/simple-string-167__ksp-a53a19561f/config.pbtxt': Operation not permitted
...
```
Since the `/models/_triton_models` dir contains files created by the adapter container which may run as a different user. Only the dir itself needs permissions set so that the adapter can write to it after it's first created.
Remove `-R` from chmod command in `triton-2.x` ServingRuntime yaml.
Avoid unnecessary errors in the log
> fix: Prevent chmod errors in log after unexpected triton restart

- .github/workflows/build-and-push.yml
- release/RELEASE_PROCESS.md
- We want to clearly outline the process of handling a new release.
- We want version tagged docker images to be pushed to DockerHub when a new release is tagged in GitHub.
- Add a release process document
- Updated build and push workflow file to also test, build, and push the image on tags.
- Clearer release process
- Tagged image versions on DockerHub.
> chore: Add release process items

- config/default/config-defaults.yaml
- controllers/config.go
- controllers/modelmesh/const.go
- controllers/modelmesh/modelmesh.go
- controllers/modelmesh/proxy.go
- controllers/modelmesh/tls.go
- controllers/predictor_controller.go
- controllers/service_controller.go
- controllers/servingruntime_controller.go
- controllers/servingruntime_controller_test.go
- controllers/testdata/servingruntime_controller.golden
- controllers/testdata/test-config-defaults.yaml
- main.go
- pkg/mmesh/modelmesh_service.go
This PR adds preliminary REST support for ModelMesh inferencing. Config options are now available for enabling a REST Proxy container to be deployed as part of a ServingRuntime deployment. 
In the `proxy` directory are the files necessary to build this proxy container. 
Related: #6
> feat: Add preliminary REST inferencing support via proxy container

- README.md
- docs/component-versions.md
Add component versions doc so the dependent versions are clearly listed
and the doc should be updated for each release when needed.
> Add component versions doc

- config/rbac/networkpolicy-runtimes.yaml
I was testing on OpenShift, and could not curl the REST proxy using NodePort/LoadBalancer service unless I added the port to the network policy.
Expose the default REST port in the ServingRuntime NetworkPolicy.
I can curl an inference result on OpenShift using a NodePort service.
> fix: Add default REST port to runtime NetworkPolicy

- docs/inferenceservice.md
- docs/quickstart.md
A doc for deploying on ModelMesh using the KServe InferenceService interface was added. 
This complements https://github.com/kserve/modelmesh-serving/pull/34
> docs: Add info about InferenceService deployment

- CONTRIBUTING.md
- docs/developer.md
New developers should probably have a document to help with onboarding. 
A basic document was created to enable users to get familiar with some of the development processes for the project.
New developers to the project now have some information for getting started.
Closes: #55
> docs: Add developer doc

- .golangci.yaml
- .pre-commit-config.yaml
- controllers/modelmesh/etcd.go
- pkg/mmesh/etcdrangewatcher.go
In #53 reported some issues, checked and fixed the ones that are code errors
Fix bug
The code error is fixed, but
- The field alignment is not fixed, not sure whether it's needed and it may have potential impact, maybe just change the golangci-lint rule to ignore it?
- Does not upgrade golangci-lint to 1.42.1 and golang to 1.7 since as mentioned it will be looked separately.
> fix: Fix code errors reported by golangci-lint

- pkg/mmesh/grpc_resolver.go
- pkg/mmesh/grpc_resolver_test.go
This is one of the changes that will be needed to make the controller multi-namespace capable
Update kube grpc client resolver to understand "service.namespace" DNS format and keep track of a resolver per namespaced service.
The Kube grpc resolver is namespace aware.
> feat: Multi-namespace grpc resolver

- config/rbac/role.yaml
- controllers/const.go
- controllers/predictor_controller.go
- controllers/service_controller.go
- controllers/servingruntime_controller.go
- controllers/suite_test.go
- main.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/mmesh/modelmesh_service.go
Motivation
The way that the kube `Service` is currently reconciled from the `ConfigMap` uses some hacks to avoid updating the Service when unrelated config changes are made, in particular the use of "special" reconcile `Request` values to indicate whether it was triggered by a config change or not.
In addition:
- The way that the `MMClient` was refreshed is not threadsafe
- Similar hacks are used for reconciling the `ServiceMonitor`
- An "old" Service would not be deleted if the service name was changed in the configuration
Modifications
- Move the general dynamic config handling into its own config package
- Move logic to generate/update a target `ServiceSpec` when the `ConfigMap` changes into this config package and protect with a mutex
- Have the service reconciler compare against this …
> refac: Refactor service controller

- .github/workflows/run-fvt.yml
- controllers/service_controller.go
- fvt/helpers.go
- pkg/mmesh/modelmesh_events.go
For multi-namespace support various different parts of the controller need to be adapted. This PR updates the ModelMeshEventStream component which streams events from modelmesh's etcd.
It's assumed that the same etcd is used for all namespaces, and that the key prefix is adjusted for non-controller namespaces to be `<root_prefix>/mm_ns/<namespace>/` (as opposed to just `<root_prefix>/` for the controller namespace).
These changes should not affect the single-namespace behaviour or existing tests.
> feat: Multi-namespace modelmesh event stream

- controllers/modelmesh/cluster_config.go
- controllers/servingruntime_controller.go
- controllers/suite_test.go
- controllers/util.go
- main.go
Rework ServingRuntime controller to work across multiple namespaces.
Includes restriction of ServingRuntime reconciliation to either the controller namespace or namespaces which have a `modelmesh-serving` annotation.
These changes should not affect the single-namespace behaviour or existing tests.
> feat: Namespace-aware serving runtime controller

- controllers/service_controller.go
- controllers/servingruntime_controller.go
- controllers/util.go
- main.go
The created Service is owned by either the controller `Deployment` or the `Namespace` resource, depending on whether RBAC permissions are present for reading `Namespace`s.
> feat: Namespace-aware Service controller

- config/runtimes/mlserver-0.x.yaml
- controllers/testdata/servingruntime_controller.golden
MLServer recently allowed the gRPC max message length to be configurable. This commit uses that variable to increase the max message length to 16 MiB which aligns with ModelMesh's default.
Reference: https://github.com/SeldonIO/MLServer/blob/release/0.5.x/mlserver/settings.py#L39
Closes: #62
> chore: Update MLServer SR to increase max grpc msg size

- docs/predictors/README.md
Links [here](https://github.com/kserve/modelmesh-serving/tree/main/docs/predictors) were out of date. 
This PR fixes the links to point to the correct markdowns.
> Fix Predictor doc broken links

- config/rbac/role.yaml
- config/rbac/role_binding.yaml
- controllers/predictor_controller.go
- controllers/service_controller.go
- controllers/servingruntime_controller.go
- scripts/install.sh
Change RBAC to enable cluster scope as the default mode
- role
- role binding
- install default
Make cluster scope as the default mode for the modelmesh serving controller, to be consistent with kserve
RBAC roles and role binding
Install default is changed to cluster scope
Controller will have cluster role and default installation is in cluster scope mode
> Change RBAC to enable cluster scope

- apis/serving/v1alpha1/servingruntime_types.go
- apis/serving/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/serving.kserve.io_servingruntimes.yaml
- config/runtimes/mlserver-0.x.yaml
- config/runtimes/triton-2.x.yaml
- config/samples/servingruntime_pullerless.yaml
- controllers/modelmesh/cluster_config.go
- controllers/modelmesh/cluster_config_test.go
- controllers/servingruntime_controller.go
- controllers/testdata/test-servingruntime.yaml
- docs/runtimes/custom_runtimes.md
- docs/runtimes/mlserver_custom.md
- fvt/fvtclient.go
- fvt/globals.go
- fvt/predictor_test.go
- fvt/testdata/predictors/foo-predictor.yaml
- fvt/testdata/runtimes/non-mm-runtime.yaml
With KServe now using ServingRuntimes, we need to make sure that the ModelMesh-Serving runtime selection logic only selects runtimes that are ModelMesh compatible.
This adds a field `multi-model` to the ServingRuntime spec which denotes if a given SR is compatible with ModelMesh or not. The default is false. ServingRuntime controller logic was adjusted to account for this field.  An e2e test was added to test this field, and example SRs in docs were updated to include this field.
ModelMesh-Serving will only consider runtimes with multiModel = true, and SMS and MMS ServingRuntimes can coexist peacefully.
Close: https://github.com/kserve/modelmesh-serving/issues/80
> feat: Introduce "multiModel" field to SR spec

- .github/workflows/run-fvt.yml
- fvt/fvt_suite_test.go
- fvt/fvtclient.go
- fvt/globals.go
- fvt/predictor_test.go
- scripts/deploy/iks/deploy-mm-serving.sh
- scripts/deploy/iks/test-fvt.sh
Enable basic FVTs for multi namespaces
- add an env variable for controller namespace
- update model-serving-config in the controller namespace
- update FVT workflow to run complete FVTs in user namespace
in addition to controller namespace
Enable and run FVTs in both controller and user namespaces in
the default cluster scope mode
1. Updated fvt code to take an env variable for controller namespace
and configure configmap in the controller namespace.
2. Add/update script in workflow and setup and run FVTs in user namespace 
The FVTs should run and pass in multiple namespaces
> Enable basic FVTs for multi namespaces

- config/runtimes/mlserver-0.x.yaml
- config/runtimes/triton-2.x.yaml
- config/samples/servingruntime_custom.yaml
- config/samples/servingruntime_pullerless.yaml
- controllers/modelmesh/cluster_config_test.go
- controllers/modelmesh/constraints_test.go
- controllers/modelmesh/model_type_labels.go
- controllers/modelmesh/model_type_labels_test.go
- controllers/testdata/test-servingruntime.yaml
- docs/runtimes/custom_runtimes.md
- docs/runtimes/mlserver_custom.md
- fvt/testdata/runtimes/non-mm-runtime.yaml
In each supported model format of a ServingRuntime, a user can specify autoSelect as true to indicate that the given ServingRuntime can be used for automatic placement of a model of that format. Kserve uses this setting for automatic model placement decisions, but MM doesn't yet currently
Logic was added to have MM only consider SRs with model formats containing autoSelect as true when finding compatible runtimes.
The out-of-the-box ServingRuntimes now have "autoSelect: true" on all of their supported formats, so there is no behavior change for users.
MM respects the autoSelect field in each supported model format entry.
> feat: Add autoSelect ServingRuntime logic

- docs/install/install-script.md
This will help to ensure that users coming to our installation documentation only use the latest stable release.
> docs: Change install instructions to use release branch

- release/RELEASE_PROCESS.md
- scripts/install.sh
A user can now optionally pass in a link to an archive file of the configs using the `-p` option of the install.sh script.
This is more of a nice-to-have that allows some flexibility with installation options.
> feat: Allow installation using link to config archive

- docs/install/install-script.md
- scripts/setup_user_namespaces.sh
Add a script file to setup additional user namespaces for modelmesh serving
controller to manage resources across multiple namespaces.
Provide script and instructions for users to enable additional namespaces for modelmesh serving.
Add a script file to setup multiple user namespaces after initial installation
Update install doc with instructions
The user can easily enable additional namespaces.
> Add script to setup user namespaces

- docs/inferenceservice.md
- docs/quickstart.md
- docs/runtimes/custom_runtimes.md
- release/RELEASE_PROCESS.md
- Updated quickstart to clone release branch
- Renamed disable to disabled which is the correct field name
- Added note about updating namespace prep script to release doc
- Removed misleading InferenceService storage spec docs as the new storage spec PR hasn't been merged yet. These can be re-added once the spec is actually updated.
> docs: Miscellaneous minor doc fixes

- controllers/modelmesh/proxy.go
- controllers/testdata/servingruntime_controller.golden
In order to keep the max gRPC message sizes aligned between ModelMesh and the REST-proxy, this PR takes the config value used by ModelMesh and passes it in to the REST-proxy as an env variable.
> chore: Propagate GrpcMaxMessageSize to REST proxy

- config/rbac/role.yaml
This change was necessary for me to get the headless service to spin-up on OpenShift 4.9
> Update permissions for namespaces/finalizers

- .tekton/pipeline.yaml
- scripts/deploy/iks/deploy-mm-serving.sh
- scripts/deploy/iks/undeploy-mm-serving.sh
Fix scripts for toolchain FVT so the InferenceService CRD
from kserve will be installed and removed
Also increase FVT retry to 2
> Fix scripts for toolchain FVT

- config/runtimes/mlserver-0.x.yaml
- controllers/predictor_controller.go
- controllers/testdata/servingruntime_controller.golden
- pkg/config/config.go
- pkg/mmesh/modelmesh_service.go
In an effort to rebase our internal wml-serving repo on the kserve/modelmesh-serving repo, we are syncing some of the differences internally externally. All of the below changes already exist internally.
- Set MLServer GRPC message size to unlimited
- This is because the MLServer GRPC message size is already limited by the `MM_SVC_GRPC_MAX_MSG_SIZE`. This allows us to only have to worry about one variable that limits the message size.
-  Refactor checking digest runtime images to see if they match the provided digest into a separate method
- Remove clientChange for rest port, do not need to reconnect to mmesh client if rest port changes
- Set changed flag if endpoints change in predictor reconciler
- In the predictor reconciler, we should update the Predictor Status if/when just the …
> chore: sync small internal changes

- docs/predictors/predictor-cr.md
Small doc update to accurately describe `httpEndpoint` predictor status field.
> docs: update httpEndpoint description

- fvt/isvc_test.go
- fvt/predictor_test.go
Occassionally during FVT runs, InferenceService inference requests would fail if run after the TLS predictor inference tests because the port-forward was not reset. This commit ensures that we disconnect in the preparation step of the ISvc tests.
> fix: Fix isvc inference fvt failure

- .tekton/pipeline.yaml
- .tekton/task.yaml
- scripts/deploy/iks/run-perf-test.sh
Add performance test to e2e toolchain
Make sure the performance is not degraded
Add a step to the end to end toolchain that runs every night to run performance tests, developed under [modelmesh-performance](https://github.com/kserve/modelmesh-performance) repo.
Performance tests will be run nightly and the step will fail if performance is worse than the threshold.
> Add performance test to e2e toolchain

- controllers/service_controller.go
A kubebuilder RBAC annotation was added to correspond to an addition in PR #130
for "namespaces/finalizers".
> chore: Add missing kubebuilder annotation

- apis/serving/common/common_types.go
- apis/serving/v1alpha1/predictor_types.go
- config/crd/bases/serving.kserve.io_predictors.yaml
- controllers/predictor_controller.go
- pkg/predictor_source/inferenceservice_registry.go
**Motivation** 
`TotalCopies` is a recently added field to the InferenceService status which tracks the number
of copies/replicas of the model. We should start using it.
**Modifications**
`TotalCopies` was added to the `PredictorStatus`, and the Predictor CRD was regenerated.
The InferenceService registry now propagates this field.
**Result**
`TotalCopies` is now available in the `Predictor` and `InferenceService` statuses.
> feat: Add TotalCopies in Predictor Status spec

- controllers/modelmesh/runtime.go
- controllers/modelmesh/runtime_test.go
We are working to align CRDs between this repo and kserve/kserve. In https://github.com/kserve/modelmesh-serving/pull/148, we mirrored updates to the ServingRuntime CRDs. This PR implements use of BuiltInAdapter.Env.
- allow values in BuiltInAdapter.Env to override environment variables added by the controller
> feat: support env overrides for the adapter

- config/dependencies/fvt.yaml
- config/dependencies/quickstart.yaml
The 'latest' tag is actually around four years old (corresponding to etcd 3.3.8), so this uses
a newer version for the quickstart/FVTs.
> chore: update quickstart/fvt etcd image tag

- controllers/modelmesh/const.go
- controllers/modelmesh/constraints.go
- controllers/modelmesh/etcd.go
- controllers/modelmesh/modelmesh.go
- controllers/modelmesh/proxy.go
- controllers/modelmesh/puller.go
- controllers/modelmesh/runtime.go
- controllers/modelmesh/runtime_test.go
- controllers/modelmesh/tls.go
- controllers/servingruntime_controller.go
- controllers/servingruntime_validator.go
- controllers/servingruntime_validator_test.go
We are working to align CRDs between this repo and kserve/kserve. In https://github.com/kserve/modelmesh-serving/pull/148, we mirrored updates to the ServingRuntime CRDs. This PR provides implementations related to the changes to the Pod spec included in the runtime: allowing additional Volumes to be specified, using the full `v1.Container` spec.
These additions allow more freedom in how a Runtime Deployment can be configured, but this also opens up more potential for conflicts with the containers injected by the controller. For this reason, this PR also adds some constraints and validation on ServingRuntimes, but attempts to mostly keep the current behavior.
- small refactors to gather and expose variables with names for internal Volumes
- use full `v1.Container` from the CRD when …
> feat: implement additions to the runtime pod spec

- controllers/modelmesh/constraints.go
- controllers/modelmesh/model_type_labels.go
- controllers/modelmesh/model_type_labels_test.go
- controllers/servingruntime_controller.go
- controllers/servingruntime_validator.go
Our code included a simple `StringSet` implementation, but there's an equivalent type in the `k8s.io/apimachinery/pkg/util/sets` package.
- Remove `StringSet` impl and associated unit tests
- Replace current use of `StringSet` with sets.String
- Use sets.String in `servingruntime_validator` rather than explicit maps
- Small fix to container port check in `servingruntime_validator`
Less/clearer code, better reuse
Signed-off-by: Nick Hill <nickhill@us.ibm.com>
> refac: Replace custom StringSet impl with apimachinery sets.String

- config/dependencies/fvt.yaml
- config/dependencies/quickstart.yaml
- docs/quickstart.md
- scripts/install.sh
The minio and etcd instances now use deployments instead of pods to provide
some level of resiliency. 
The quickstart doc was also updated with a small disclaimer about these deployments.
> chore: convert quickstart/fvt pods into deployments

- controllers/modelmesh/modelmesh.go
- controllers/servingruntime_controller.go
- main.go
During unrelated testing I found a bug where a nil pointer deref could occur if ServingRuntimes are encountered in namespaces in which modelmesh isn't enabled (i.e. not the controller's namespace and without the `modelmesh-enabled=true` label).
- Move list pointer initialization to ensure it won't be nil
- Improve some badly worded log statements and one containing excessive detail (full deployment contents rather than just name)
Signed-off-by: Nick Hill <nickhill@us.ibm.com>
> fix: Fix possible nil pointer dereference; minor log improvements

- .github/workflows/run-fvt.yml
**Motivation**
Kubeflow/KServe are targeting K8s 1.22, so ModelMesh functional tests should test on this version.
**Modifications**
The GitHub Actions workflow for FVTs was increased to 1.22.10 from 1.20.7. The Minikube version used
was also increased.
**Result**
Functional tests now run on K8s 1.22.
> chore: Update K8s version in GH Actions FVTs

- controllers/modelmesh/cluster_config.go
- fvt/fvtclient.go
- fvt/predictor/predictor_test.go
**Motivation**
Enable users to use the KServe v2 ModelMetadata endpoint with Triton and MLServer ServingRuntimes.
**Modifications**
- ModelMetadata added to dataplane config in controller.
- Some functional tests were added to test the newly exposed endpoint.
**Result**
Users can send gRPC requests to the ModelMetadata endpoint. Primarily useful with Triton as MLServer only seems to return the name of the model.
Partially-Closes: #136
> feat: Enable ModelMetadata endpoint

- .github/workflows/run-fvt.yml
- Makefile
- config/crd/bases/serving.kserve.io_clusterservingruntimes.yaml
- config/crd/bases/serving.kserve.io_inferenceservices.yaml
- config/crd/bases/serving.kserve.io_servingruntimes.yaml
- config/crd/kustomization.yaml
- scripts/deploy/iks/deploy-mm-serving.sh
Currently modelmesh-serving does not include the `InferenceService` CRD manifest, but will work with it if it's been previously installed (via an install of the main kserve controller). Since we will be encouraging everyone to use this in preference to the `Predictor` CRD, it would be good if it was available by default in standalone modelmesh installations.
- Copy manifests of common CRDs including inferenceservices from https://github.com/kserve/kserve/tree/master/config/crd
- No longer pull from kserve for fvt tests
- Update make manifests target to include v1beta1
`InferenceService` CRD will be available to use when using modelmesh-serving "standalone" without having to obtain it manually from the kserve/kserve repo.
> chore: Include InferenceService CRD in standalone mm-serving install

- docs/monitoring.md
This doc adds some information about how to set up a monitoring stack using Prometheus and Grafana.
A list of exposed metrics is also provided.
Co-authored-by: Sri Venkateshwara Kishore Kumar Goutham <vegoutha@in.ibm.com>
Co-authored-by: Nick Hill <nickhill@us.ibm.com>
Co-authored-by: Angel Luu <angel.luu@us.ibm.com>
> docs: Add monitoring/metrics doc

- docs/configuration/README.md
- docs/configuration/tls.md
Surface some internal TLS configuration documentation externally.
> docs: Add tls configuration docs

- pkg/predictor_source/inferenceservice_registry.go
- pkg/predictor_source/inferenceservice_registry_test.go
The model puller now supports pulling from Azure Blob Storage. We should allow users to pass in an
Azure Blob Storage URI as an InferenceService Predictor `storageUri`.
Storage parsing logic now parses Azure Blob URIs and passes the relevant info the puller.
Users can now pass in Azure Blob Storage URIs as part of `storageUri`.
> feat: Support azure blob storageURIs in Isvc

- docs/README.md
- docs/configuration/README.md
- docs/install/README.md
- docs/predictors/run-inference.md
Added some docs about rest-proxy that was added internally but not externally.
Also updated the deployment components resource usage chart and added some missing OVMS references.
> docs: Add rest-proxy docs

- config/rbac/leader_election_role.yaml
- config/rbac/leader_election_role_binding.yaml
- config/rbac/restricted_scc_role.yaml
- config/rbac/restricted_scc_role_binding.yaml
- config/rbac/role.yaml
- config/rbac/role_binding.yaml
The role/rolebinding names should be more specific to enhance clarity of purpose
and to avoid potential naming collisions.
Prepended a `modelmesh-` prefix to relevant names. 
More clarity for what each role/rolebindings belongs to.
> chore: Rename roles/rolebindings

- scripts/deploy/iks/run-perf-test.sh
Update performance test script to deploy the predictor first
to ensure it is up and runnig before k6 is executed during
pipeline runs.
It takes about 20 seconds in test environments so the retry
loop will last for 60 seconds to be safe.
> Update performance test script for e2e pipeline

- pkg/mmesh/etcd_secret.go
- scripts/install.sh
Fix the etcd endpoints issue when etcd is in different namespace
as described in https://github.com/kserve/modelmesh-serving/issues/186
The default etcd connection endpoints in quick start and fvt yaml are
changed to be placceholder based, and will be replaced during the
install script run. The etcd secret propagation will no longer assume
that etcd resides in the controller namespace.
> Fix etcd endpoints when etcd is in different namespace

- docs/model-runtime.proto
The docs dir in this repo contains a copy of the `model-runtime.proto` service definition from the model-mesh repo. It was [recently updated](https://github.com/kserve/modelmesh/pull/50) with clearer comments for a couple of the RPC methods.
Sync the latest version to this repo.
Signed-off-by: Nick Hill <nickhill@us.ibm.com>
> doc: Sync updated model-runtime.proto file from modelmesh repo

- controllers/modelmesh/modelmesh.go
- controllers/testdata/servingruntime_controller.golden
Kubernetes starts containers sequentially in order, which can mean the start of later containers is held up if their images have to be pulled. For large model server images this can cause a problem because model-mesh waits for a limited amount of time at startup for the runtime to become ready before returning ready from its own probe.
Making the `mm` container last in the list ensures that no image pulling time will be included in this startup polling time and avoids unnecessary timeouts / extended readiness probe failures.
- Add `ensureMMContainerIsLast` function to runtime deployment reconciliation logic which runs after other modifications to the pod spec.
- Update unit test fixtures accordingly
More stable deployments in cases where the model server image takes a long time to pull. …
> feat: Ensure modelmesh container comes last in list

- scripts/delete.sh
The `delete.sh` cleanup script currently doesn't require a namespace to be provided via the -n option and uses the current kubectl context's namespace otherwise. The `$namespace` variable wasn't set in this case however meaning later parts of the script might not work as intended.
Ensure `$namespace` variable is set correctly either way.
`delete.sh` script works properly when `-n` option isn't used.
> fix: Ensure delete.sh script works properly with implicit namespace

- config/default/config-defaults.yaml
- controllers/servingruntime_controller.go
- controllers/servingruntime_validator.go
- controllers/servingruntime_validator_test.go
- controllers/suite_test.go
- fvt/tls.go
- pkg/config/config.go
- pkg/config/config_test.go
Model-mesh serving makes use of a single adapter image to interface with a number of "built-in" model server types, currently comprising `triton`, `mlserver`, `ovms`.
Currently which kind of adapter to run is controlled by the entrypoint to the adapter container within the modelmesh pods, which is set by the controller based on the `builtInAdapter.serverType` field of the `ServingRuntime` CRD.
However this is currently validated against a hardcoded list of type strings meaning that any extensions to the runtime adapter image to support new kinds of model servers also require a code change and rebuild of the controller image.
Move the list of supported built-in server types to a list in the global config.
Update controller validation logic and tests accordingly.
The shared built-in runtime …
> feat: Make list of supported built-in runtime server types overridable

- controllers/modelmesh/runtime.go
- controllers/testdata/servingruntime_controller.golden
It may be useful for some built-in runtime adapters to have the model server's inferencing endpoint information in addition to the existing "management" port number that's passed (in case it is different).
- Set a new `RUNTIME_DATA_ENDPOINT` env var on the built-in adapter container
- Parse the `ADAPTER_PORT` env var value from the ServingRuntime `grpcEndpoint` field instead of hardcoding to 8085
> feat: Pass ServingRuntime inference endpoint to built-in adapter

- docs/quickstart.md
There is a [dead link](https://github.com/kserve/modelmesh-serving/blob/main/docs/install/environment.md#deployed-components) in the **Prerequisites** section of the [Quickstart guide](https://github.com/kserve/modelmesh-serving/blob/main/docs/quickstart.md#prerequisites).
Update to the correct link to the **"[Deployed Components](https://github.com/kserve/modelmesh-serving/blob/main/docs/install/README.md#deployed-components)"**.
Link works again.
/cc @njhill @chinhuang007
> doc: Update cluster sizing link in quickstart.md

- docs/quickstart.md
- scripts/delete.sh
- scripts/install.sh
- scripts/setup_user_namespaces.sh
Developers who work on both Kubeflow and ModelMesh must use different versions of the `kustomize` CLI as Kubeflow installation requires version no greater than `3.2.0` yet ModelMesh installation requires a version greater than `4.0.0`.
There have been previous changes to the install scripts attempting to tolerate older `kustomize` versions, yet for `3.2` it is still causing errors like these:
```
...
Installing ModelMesh Serving built-in runtimes
Error: unknown flag: --load-restrictor
error: no objects passed to apply
```
This is because various versions of `kustomize` produce differently formatted output and the ModelMesh install scripts do not capture the intended semantic version identifier, i.e.
```Bash
$ kustomize version  # 3.2
Version: {KustomizeVersion:3.2.0 …
```
> fix: Tolerate kustomize version 3.2

- docs/predictors/run-inference.md
- docs/quickstart.md
The code snippet to `port-forward` the `modelmesh-serving` service did not work:
```Bash
$ kubectl port-forward modelmesh-serving 8033:8033
Error from server (NotFound): pods "modelmesh-serving" not found
```
Update the code snippet to specify the resource type `service`:
```Bash
$ kubectl port-forward service/modelmesh-serving 8033:8033
```
```
Forwarding from 127.0.0.1:8033 -> 8033
Forwarding from [::1]:8033 -> 8033
Handling connection for 8033
```
/cc @njhill 
/cc @chinhuang007
> doc: fix port-forward command in run-inference.md

- fvt/README.md
After many attempts to run the FVT tests it became clear that an undersized Kubernetes cluster (insufficient resources) prevented the FVTs to succeed.
Update the FVT README with a Prerequisite section that outlines the required CLIs and the minimum cluster size.
The FVT tests completed successfully.
/cc @njhill @chinhuang007
> doc: Update FVT prerequisites

- .gitignore
- scripts/develop.sh
When using the containerized development environment (`make develop`) to test changes to the ModelMesh source code or running FVT tests all command history is lost from session to session -- which negatively impacts productivity.
The ModelMesh develop container runs as root and needs the command history file mounted under the `/root/` directory, not `/workspace/`
The develop container command history is preserved from one `make develop` session to the next.
/cc @njhill @chinhuang007
> chore: Preserve command history from `make develop` sessions

- Makefile
- docs/configuration/README.md
- docs/inference/data-types-mapping.md
- docs/model-formats/advanced-configuration.md
- docs/predictors/README.md
- docs/runtimes/custom_runtimes.md
- scripts/verify_doc_links.py
Broken links in documentation are making it harder for new comers to learn about ModelMesh and often it is not easy to find what the correct link should be. For project maintainers it is time consuming to revisit documentation to identify broken links manually and it certainly does not make the best impression on new comers if they click on links that return 404 errors.
Add new script `scripts/verify_doc_links.py` and new `Make` target `check-doc-links` to identify broken links in any of the currently 211 links in 43 Markdown files.
```Bash
$ make check-doc-links
```
```YAML
Checked 211 links (144 unique URLs) in 43 Markdown files.
docs/configuration/README.md:68: /docs/configuration/predictors/run-inference -> 404
docs/inference/data-types-mapping.md:5: …
```
> chore: Add script to identify broken doc links

- docs/quickstart.md
Until ModelMesh release 1.0 the [Quickstart guide](https://github.com/kserve/modelmesh-serving/blob/main/docs/quickstart.md) should require `kustomize` version `4.0.0`+ since the ModelMesh 0.9 release does not yet have the [install script fixes](#233) to tolerate older versions of the `kustomize` CLI.
After the ModelMesh 1.0 release, the Quickstart doc should be changed to allow `kustomize` version `3.2.0` since that next release will include the respective install script fixes (#233) to tolerate older versions of `kustomize`.
Fixes #243
Reinstate the `kustomize` v`4.0.0`+ prereqs in the Quickstart guide.
The required version of `kustomize` in the Quickstart guide matches what the install and delete scripts support.
Create a new issue to change the Quickstart guide to allow `kustomize` …
> docs: Reinstate Quickstart kustomize v4.0.0 prerequisite

- scripts/verify_doc_links.py
In its current version the `verify_doc_links.py` script excludes any URLs that contain a colon `:` character.
This was meant to exclude any local URLs with a port like "`:8008`". Instead it excludes any URLs that start with "`http:`" or "`https:`". The "rookie" who created that script! 🙄 
Remove the ":" from the list of patterns to identify URLs that should be excluded from the link verification.
220 links found instead of 211 before.
> chore: Fix error in `verify_doc_links.py` script

- .gitignore
- docs/developer.md
- fvt/README.md
- scripts/develop.sh
When using the containerized development environment `make develop` to run FVT tests, one needs to configure access to a Kubernetes or OpenShift cluster from inside the container. Which has to be done for every `make develop` session. This can be tricky when cloud provider specific CLI tools are needed to connect and authenticate to a cluster.
Currently there is a short paragraph in the FVT README about how to export a minified kubeconfig file and create that inside the container. It is tedious to repeat those steps for each `make develop` session and depending on OS, shell environment, editors and possible text encoding issue it is also error prone.
This PR proposes to automatically create the kubeconfig file in a local and git-ignored directory inside the local project and automatically …
> chore: Automatically set kube context in development container

- controllers/config/manifest.go
- controllers/modelmesh/modelmesh.go
- controllers/service_controller.go
- controllers/servingruntime_controller.go
- main.go
Fix a couple of bugs for ClusterServingRuntime and also rename two variables to reflect the cluster scope mode is enabled
Fix bugs and make code more readable
> fix: Fix a couple of bugs for ClusterServingRuntime

- config/runtimes/kustomization.yaml
Intel have released a new version of OpenVINO Model Server which now supports the KServe V2 prediction API (in addition to existing V1 API support): https://github.com/openvinotoolkit/model_server/releases/tag/v2022.2
Update OVMS image tag from 2022.1 to 2022.2 in the ServingRuntime configuration.
KServe V2 API can be used with OpenVINO Model Server and model-mesh.
> chore: Update to use latest OVMS 2022.2 image

- docs/configuration/tls.md
The script snippet in our TLS docs for creating a configmap with the TLS secret name parameter included incorrect yaml which would not result in TLS being enabled. It should be:
```yaml
data:
config.yaml: |
tls:
secretName: ${SECRET_NAME}
```
instead of
```yaml
data:
config.yaml: |
tls.secretName: ${SECRET_NAME}
```
- Fix the config yaml
- Change `kubectl apply` to `kubectl create` to avoid overwriting existing config
- Add `> ca.crt` to the cert retrieval command
- Replace `oc` with `kubectl` in Certificate CR example
Correct docs.
Signed-off-by: Nick Hill <nickhill@us.ibm.com>
> docs: Fix TLS secret name ConfigMap update example

- Makefile
- scripts/build_devimage.sh
- scripts/build_docker.sh
This PR will update the makefile and build scripts to allow developers to use podman as the build engine.
The default behaviour for the makefile will remain the same.
I ran the following to build images:
```
make build.develop ENGINE=podman
make build ENGINE=podman
```
I don't have a working docker env to test in.
cc @njhill
> feat: Update makefile to support building with podman

- docs/quickstart.md
Output in the Quickstart documentation doesn't capture all three `ServingRuntime`s. Potentially just missed in #167.
Update output and supported frameworks to include OpenVINO.
More accurate documentation for new users.
> docs: Update quickstart to include ovms

- config/manager/manager.yaml
The pod anti-affinity will tell the Kubernetes schedule to schedule pods on different nodes if possible. This will allow users to enable HA by setting the number of replicas to a number greater than 1.
> feat: Enable HA by default for Modelmesh Controller

- .github/workflows/run-fvt.yml
- README.md
- config/default/config-defaults.yaml
- config/runtimes/kustomization.yaml
- config/runtimes/torchserve-0.x.yaml
- controllers/modelmesh/cluster_config.go
- controllers/servingruntime_controller_test.go
- controllers/testdata/servingruntime_controller.golden
- fvt/predictor/predictor_suite_test.go
- fvt/scaleToZero/scaleToZero_suite_test.go
- pkg/config/config.go
The Triton runtime can be used with model-mesh to serve PyTorch torchscript models, but it does not support arbitrary PyTorch models i.e. eager mode. KServe "classic" has integration with TorchServe but it would be good to have integration with model-mesh too so that these kinds of models can be used in distributed multi-model serving contexts.
The bulk of the required changes are to the adapter image, covered by PR https://github.com/kserve/modelmesh-runtime-adapter/pull/34.
This PR contains the minimal controller changes needed to enable the support:
- TorchServe ServingRuntime spec
- Add "torchserve" to the list of supported built-in runtime types
- Add "ID extraction" entry for TorchServe's gRPC Predictions RPC so that model-mesh will automatically extract the model name from …
> feat: TorchServe support

- docs/runtimes/README.md
- docs/runtimes/mlserver_custom.md
While creating a Python-based custom runtime, I found that some of the documentation and templates could be a bit more helpful with naming conventions, hints, and formatting to match the [MLServer built-in runtime](https://github.com/kserve/modelmesh-serving/blob/main/config/runtimes/mlserver-0.x.yaml) for ease of comparison.
Copy-edited docs while adding help and clarification to templates.
Friendlier documentation for building and deploying custom runtimes.
> docs: Update Custom Runtime Docs

- config/runtimes/torchserve-0.x.yaml
Fix FVT runtime count issue by making torchserve as cluster serving runtime as default, similar to other out-of-the-box runtimes
Make FVT working in the default cluster scoped mode
Change torchserve-0.x to be a ClusterRuntime
Add a line to e2e FVT to disable torchserve-0.x, similar to github actions
FVT working in cluster scoped mode
e2e working
> Fix FVT runtime count issue

- config/manager/manager.yaml
- pkg/config/config.go
The file containing the default configuration for the ModelMesh Controller is called `config-defaults.yaml`, which resides in a directory also called `config-defaults.yaml` as pointed out by @adrwong-lora in issue #205
```
/etc/model-serving/config-defaults.yaml/config-defaults.yaml
```
Change `mountPath` from `/etc/model-serving/config-defaults.yaml` to `/etc/model-serving/config/default`
The file containing the default configuration file after this fix:
```
/etc/model-serving/config/default/config-defaults.yaml
```
Which more closely reflects the path of the [`config-defaults.yaml`](https://github.com/kserve/modelmesh-serving/blob/main/config/default/config-defaults.yaml) file in the `modelmesh-serving` repository:
```
config/default/config-defaults.yaml
```
Resolves #205 
/cc @njhill …
> fix: config-defaults mount path

- Dockerfile
- Dockerfile.develop
- go.mod
- go.sum
1. Update the ModelMesh Controller image to use the UBI 8.7 minimal base image
2. Updated Go version to the latest fix pack version.
Signed-off-by: JasmondL <Jasmond.Ming.Quan.Loh@sap.com>
Authored-by: JasmondL <Jasmond.Ming.Quan.Loh@sap.com>
Co-authored-by: JasmondL <Jasmond.Ming.Quan.Loh@sap.com>
> chore: Update Dockerfile packages (#291)

- docs/component-versions.md
- docs/install/install-script.md
- docs/quickstart.md
- scripts/setup_user_namespaces.sh
Follow [release process step 3](https://github.com/kserve/modelmesh-serving/blob/main/release/RELEASE_PROCESS.md#publish-the-release)
> 3. Update `docs/component-versions.md`, `docs/quickstart.md`, `docs/install/install-script.md`, and `scripts/setup_user_namespaces.sh` files in the `main` branch with the same versions as above, then submit this as a PR to `main`. Wait for @njhill to merge.
/cc @njhill 
/assign @njhill
> Update docs with version `v0.10.0-rc0`

- docs/install/install-script.md
- docs/quickstart.md
- scripts/install.sh
Quickstart should use namespace scope mode for simplicity. In current version there is an inconsistency wrt `ServingRuntimes` vs `ClusterServingRuntimes`.
- `docs/install/install-script.md` (correct a typo)
- `docs/quickstart.md` (change install command for ns scope mode and add missing `torchserv` serving runtime)
- `scripts/install.sh` (fix `sed -i` commands)
Quickstart install steps work like a charm again :-)
Once merged into `main`, we will need to update the `release-0.10` branch as well
---
/cc @njhill 
/assign @njhill
> Use `--namespace-scope-mode` for Quickstart

- docs/install/install-script.md
There doesn't seem to be much information about what the `--namespace-scope-mode` flag does, or the difference between cluster-scoped and namespace-scoped serving runtimes.
- As a start, a blurb is included for the `--namespace-scope-mode` flag in the `install-script` doc.
- Corrects the `--help` output as well.
Helpful information about the `--namespace-scope-mode` which is included in the recommended way to use the quick-start install of ModelMesh.
> doc: include namespace-scope info

- config/dependencies/quickstart.yaml
Addressing file access permission issues on OpenShift reported in issues #210 and #215 for the `etcd` deployment.
Adding `data-dir` parameter to the container `args`:
```
- --data-dir
- /tmp/etcd.data
```
The `etcd` pod comes up fine and spot-testing a few basic use cases went fine. I tested on IBM Cloud Kubernetes 1.24 and OCP 4.10
---
Resolves #210
Resolves #215
> fix: etcd pod fails to start on OpenShift

- docs/quickstart.md
New users with limited exposure to gRPC or `grpcurl` can run into trouble using the inference request example provided in the quickstart example.
Add information regarding where exactly to run the gRPC inference request so that the `--proto` path used in the request finds the file and works.
Closes #67
> docs: clarify gRPC quickstart example

- controllers/modelmesh/modelmesh.go
Links pointing to ModelMesh environment variables are no longer accurate.
Update the line numbers to point to the correct places in [ModelMeshEnvVars.java](https://github.com/kserve/modelmesh/blob/main/src/main/java/com/ibm/watson/modelmesh/ModelMeshEnvVars.java)
> fix: update links to env var lines

- controllers/modelmesh/const.go
- controllers/modelmesh/modelmesh.go
- controllers/modelmesh/puller.go
- controllers/modelmesh/puller_test.go
- controllers/modelmesh/runtime.go
- controllers/predictor_controller.go
- controllers/servingruntime_controller.go
- docs/configuration/README.md
- fvt/predictor/predictor_test.go
- main.go
- pkg/config/config.go
- pkg/predictor_source/inferenceservice_registry.go
Support PVC as a storage option, to address issue https://github.com/kserve/modelmesh-serving/issues/230
- Add PVCs to deployment
- Add secret watch to ServingRuntime controller to update deployment
- Add logic to ServingRuntime controller to create PVCs for predictors if the global setting is true
- Create volumes and PVCs based on deployment for ServingRuntimes
- Update Predictor controller to validate for PVCs
- PVCs are read from the storage secret and created for all ServingRuntimes
- PVCs are read from the predictor spec and created for all ServingRuntimes if the global setting is true
- https://github.com/kserve/modelmesh-serving/issues/230
- https://github.com/kserve/modelmesh-runtime-adapter/pull/36
---
Resolves #230
> Feat: Add PVC storage support

- .github/workflows/run-fvt.yml
- config/default/config-defaults.yaml
- config/manager/kustomization.yaml
- docs/component-versions.md
- docs/install/install-script.md
- docs/quickstart.md
- scripts/setup_user_namespaces.sh
Tech preview release including:
- #230
- #337
- #284
1. Create new tech preview release tag `v0.11.0-alpha` in these repositories:
2. Verify image tags were pushed to [DockerHub](https://hub.docker.com/u/kserve):
**Updated**:
**Unchanged**: 
3. Update the container image tags to the corresponding release versions for:
**Updated**:
- `kserve/modelmesh` -> `v0.11.0-alpha`
- `kserve/modelmesh-controller` -> `v0.11.0-alpha`
- `kserve/modelmesh-runtime-adapter` -> `v0.11.0-alpha`
**Unchanged:**
- `kserve/modelmesh-minio-examples` -> `v0.10.0`
- `kserve/rest-proxy` -> `v0.10.0`
The version tags should be updated in the following files:
`Installation` section to the new `release-*` branch name
_"Get the latest release"_ section to the new `release-*` branch name
> release: Prepare v0.11.0-alpha release

- scripts/install.sh
- scripts/self-signed-ca.sh
I experienced a few errors when running the install script using the `--enable-self-signed-ca` flag from the recently merged #342. 
- Use `sed -i.bak` to work around different versions of it, originally resulting in `sed: -i: No such file or directory` for me.
- Fix `--dry-run` error which requires a set value [(none, server, or client)](https://stackoverflow.com/questions/69531858/what-is-the-different-dry-run-opportunities)
- Fix typos
Fixes errors associated with the `--enable-self-signed-ca` flag
> fix: Generalizes sed and fixes dry-run cmd

- docs/quickstart.md
The quickstart instructions explicitly install the latest release `v0.10` which does not include the recently added `--enable-self-signed-ca` or require info regarding webhook certificates. Following the document as-is results in an `Unknown option` error. 
- Remove the `--enable-self-signed-ca` option from the quickstart guide and webhook information. 
- Quickstart guide is functional for quick installation and deployment using the latest release `v0.10` 
Resolves #370
> doc: Remove cert flag from quickstart

- controllers/modelmesh/runtime.go
- controllers/testdata/servingruntime_controller.golden
Quickstart deployment of an `InferenceService` fails on Macs with M1 chip. The `modelmesh-serving-mlserver-0.x` pod does not deploy because of an affinity restriction to `amd64`.
```
Events:
Type     Reason            Age   From               Message
----     ------            ----  ----               -------
Warning  FailedScheduling  17s   default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```
```
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: kubernetes.io/arch
operator: In
values:
- amd64
```
**Source**:
https://github.com/kserve/modelmesh-serving/blob/1b3d30ac089d729bfe59e91c395a977e347aaad …
> Support ARM 64 bit architecture

- .github/workflows/fvt.yml
- config/runtimes/kustomization.yaml
- fvt/predictor/predictor_suite_test.go
- fvt/predictor/predictor_test.go
- fvt/testdata/predictors/tf-predictor.yaml
The default Triton serving runtime in ModelMesh hasn't been updated for a while. The [latest version is 23.04](https://github.com/triton-inference-server/server/releases/tag/v2.33.0).
- TritonServer image version in the default serving runtime and FVTs were updated from 21.06.1 to 23.04
- Error message(s) were updated in FVT
- The default Triton serving runtime will now deploy using the 23.04 Triton image.
- Closes #358
> chore: Update TritonServer to 23.04

- config/default/config-defaults.yaml
- config/dependencies/quickstart.yaml
- config/manager/kustomization.yaml
- docs/component-versions.md
- docs/install/install-script.md
- docs/quickstart.md
- scripts/setup_user_namespaces.sh
**Create release tags (`v0.11.0-rc0`) in these repositories:**
**Verify image tags got pushed to [DockerHub](https://hub.docker.com/u/kserve):**
**Update versions in the following files:**
**Compare to tag updates for `v0.10.0-rc0` release:**
- https://github.com/kserve/modelmesh-serving/pull/296
> release: Update image tags for v0.11.0-rc0

- .github/workflows/fvt.yml
- Dockerfile.develop
- Makefile
- controllers/hpa/hpa_reconciler.go
- fvt/fvtclient.go
- fvt/hpa/hpa_test.go
With Kubernetes version 1.23+, `autoscaling/v2beta2` (HPA) was deprecated. In Kubernetes version 1.26+ it is no longer available.
- Update Go code to use `autoscaling/v2`
- setup-envtest for unit tests to use Kubernetes version 1.23+ for `autoscaling/v2` to be available
- Update FVT to use Kubernetes version 1.26+
- Closes #402
- Related to #374
> chore: Bump to use autoscaling/v2

- .github/workflows/build.yml
Sometimes the GitHub action to push images does not get triggered despite apparently all filter conditions being met.
Add [`on: workflow_dispatch`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) to build/push action workflow.
To trigger a workflow in a repository, the user has to be a collaborator with Write permission in the repository. External users can’t trigger workflows in the repository.
TBD
> chore: Add manual trigger to run build/push action

- .github/workflows/fvt.yml
- config/default/config-defaults.yaml
- config/dependencies/fvt.yaml
- config/dependencies/quickstart.yaml
- config/manager/kustomization.yaml
- docs/component-versions.md
- docs/install/install-script.md
- scripts/setup_user_namespaces.sh
**Create release tags (`v0.11.0-rc1`) in these repositories:**
**Verify image tags got pushed to [DockerHub](https://hub.docker.com/u/kserve):**
**Update versions in the following files:**
> release: Update image tags for v0.11.0-rc1

- docs/quickstart.md
https://github.com/kserve/modelmesh-serving/issues/366#issuecomment-1593644305
Add note to Quick Start Guide for link to the last stable release.
Added note in the main [Quick Start Guide](https://github.com/kserve/modelmesh-serving/blob/main/docs/quickstart.md) as agreed by comment.
> doc: Update quickstart.md

- .github/workflows/fvt.yml
- controllers/modelmesh/modelmesh.go
- docs/component-versions.md
- docs/install/install-script.md
- docs/production-use/README.md
- docs/quickstart.md
- docs/release-process.md
- fvt/README.md
- scripts/setup_user_namespaces.sh
Several docs are still pointing to the previous release or are inconsistent in that the latest doc files from the `main` branch point to incompatible resources on the previous `release-0.10` branch or tagged release `v0.10.0`.
- add tags when pre-pulling images for FVT (`latest`, `v...`)
- pre-pull minio-examples and minio-dev-examples images for FVT
- one reason for the frequent timeouts in the FVT setup nodes
- predictor tests using minio-dev-examples
- storage tests for PVC using minio-examples (non -dev-)
- update links to `modelmesh` environment variables
- update install-script and quickstart to clone `main` branch, adding note pointing to the most recent stable release, and re-including the self-signed cert flag (#364)
- update required minimum Kubernetes version to `1.23` (HPA …
> doc: Update docs for release v0.11.0

- .github/workflows/fvt.yml
- config/default/config-defaults.yaml
- config/dependencies/fvt.yaml
- config/dependencies/quickstart.yaml
- config/manager/kustomization.yaml
- docs/component-versions.md
- docs/install/install-script.md
- scripts/setup_user_namespaces.sh
**Create release tags (`v0.11.0`) in these repositories:**
**Verify image tags got pushed to [DockerHub](https://hub.docker.com/u/kserve):**
**Update versions in the following files:**
> release: Update ModelMesh image tags to v0.11.0

- config/default/webhookcainjection_patch.yaml
- config/webhook/manifests.yaml
- scripts/self-signed-ca.sh
We need to rename the `servingruntime.serving.kserve.io` validating webhook in ModelMesh to resolve a naming conflict in `kserve/kserve`:
https://github.com/kserve/kserve/actions/runs/5741094894/job/15561730774#step:10:209
```
helm install kserve charts/kserve-resources/ --wait --timeout 180s
...
Error: INSTALLATION FAILED: 1 error occurred:
* validatingwebhookconfigurations.admissionregistration.k8s.io "servingruntime.serving.kserve.io" already exists
make: *** [Makefile:128: deploy-helm] Error 1
Error: Process completed with exit code 2.
```
https://github.com/kserve/kserve/pull/3031#discussion_r1284696404_
Rename the `servingruntime.serving.kserve.io` to `modelmesh-servingruntime.serving.kserve.io`.
TBD
FYI @sivanantha321 @Jooho
> chore: Rename webhook (HPA)

- fvt/fvtclient.go
- fvt/predictor/predictor_suite_test.go
- fvt/storage/storage_test.go
Address most frequent of the recent FVT failures due to exceeded timeouts:
- **Predictor test suite fails to initialize**:
https://github.com/kserve/modelmesh-serving/actions/runs/6017567397/job/16324018749
```
[SynchronizedBeforeSuite] [FAILED] [39.405 seconds]
[SynchronizedBeforeSuite] 
/home/runner/work/modelmesh-serving/modelmesh-serving/fvt/predictor/predictor_suite_test.go:34
Timeline >>
2023-08-29T21:29:31Z	INFO	Initializing test suite
2023-08-29T21:29:31Z	INFO	Using environment variables	{"NAMESPACE": "modelmesh-serving", "SERVICENAME": "modelmesh-serving", "CONTROLLERNAMESPACE": "modelmesh-serving", "NAMESPACESCOPEMODE": false}
2023-08-29T21:29:31Z	INFO	FVTClientInstance created	{"client": {"Interface":{}}}
2023-08-29T21:29:31Z	INFO	Delete all predictors ...
2023-08-29T21:29:33Z …
```
> test: Increase initial time to stabilize for FVTs

- .golangci.yaml
- controllers/modelmesh/constraints.go
- controllers/modelmesh/model_type_labels.go
- controllers/modelmesh/model_type_labels_test.go
- controllers/servingruntime_validator.go
To address deprecation warnings which appeared after updating to Go 1.19 in #379
Updated deprecated code following [`sets` package doc](https://pkg.go.dev/k8s.io/apimachinery/pkg/util/sets#String), e.g.:
> `use generic Set instead. new ways: s1 := Set[string]{} s2 := New[string] ()`
Resolves #386
> chore: use generic Set instead of deprecated sets.String 

- scripts/delete.sh
This fix https://github.com/kserve/modelmesh-serving/issues/399
Add a logic to check if there is a certificate object to generate for webhook or not. If not, it excludes cert-manager objects from manifests when it tries to delete `modelmesh-serving` objects
`delete.sh` always works to delete `modelmesh-serving` objects.
> fix: Update delete.sh to support self-sign-certs

- scripts/delete.sh
- scripts/install.sh
- scripts/setup_user_namespaces.sh
Closes #427 
Kustomize version `(devel)` is not supported by the install script.
Changed the regex so `(devel)` is a supported version.
Install script now works when Kustomize is installed from https://kubectl.docs.kubernetes.io/installation/kustomize/source/
> Support development version of Kustomize in install script

- controllers/service_controller.go
- controllers/util.go
Add a ClusterScope condition statement to list namespace that is only allowed for cluster scope.
Resolves #433
> fix: namespace-scoped mode by service_controller

- .github/workflows/build.yml
- .github/workflows/fvt.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- config/default/config-defaults.yaml
- config/dependencies/quickstart.yaml
- config/manager/kustomization.yaml
- controllers/modelmesh/modelmesh.go
- docs/component-versions.md
- docs/install/install-script.md
- docs/quickstart.md
- scripts/setup_user_namespaces.sh
**Create release tags (`v0.11.1`) in these repositories:**
**Verify image tags got pushed to [DockerHub](https://hub.docker.com/u/kserve):**
**Update versions in the following files:**
> release: Update image tags for v0.11.1

- controllers/hpa/hpa_reconciler.go
Address code scanning alerts 1, 2, 3:
- https://github.com/kserve/modelmesh-serving/security/code-scanning/1
- https://github.com/kserve/modelmesh-serving/security/code-scanning/2
- https://github.com/kserve/modelmesh-serving/security/code-scanning/3
> fix: Incorrect conversion between integer types

- .gitignore
- controllers/modelmesh/modelmesh.go
- docs/model-formats/openvino-ir.md
- docs/predictors/run-inference.md
- docs/predictors/setup-storage.md
- docs/quickstart.md
- fvt/README.md
- Add doc link to MM_PAYLOAD_PROCESSORS variable in modelmesh repo
- Update defunct links for OpenVINO docs
- Update single-entry 1-dimensional tensor shapes
- CamelCase Modelmesh
- Add create namespace command to FVT setup instructions
- Add command to delete namespace in Quickstart cleanup instructions -
> docs: Minor documentation fixes

- .github/workflows/codeql.yml
Add CodeQL vulnerability scan configuration.
FYI @njhill @tjohnson31415
> chore: Create CodeQL configuration file

- .github/workflows/fvt-base.yml
- .github/workflows/fvt-cs.yml
- .github/workflows/fvt-ns.yml
- scripts/install.sh
Our current FVT setup only tests ModelMesh Serving deployed in cluster-scope mode. Issue [#433](https://github.com/kserve/modelmesh-serving/issues/433#issuecomment-1738022152) revealed that this is insufficient as it missed a major regression that only surfaced when ModelMesh Serving was deployed in namespace-scope mode. The namespace-scope mode is used for the [Quickstart installation](https://github.com/kserve/modelmesh-serving/blob/main/docs/quickstart.md#run-the-installation-script) which makes any such regressions very visible.
```shell
./scripts/install.sh --namespace-scope-mode --namespace modelmesh-serving --quickstart ...
```
- Transform the current FVT workflow into a [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview): …
> test: Add FVT in namespace-scope mode

- go.mod
- go.sum
Update [google.golang.org/grpc](https://pkg.go.dev/google.golang.org/grpc) from v1.55.0 to v1.56.3 
- https://github.com/kserve/modelmesh-serving/security/dependabot/10
> chore: Updates gRPC dependencies

- Dockerfile.develop
Build/test failures due to using Python36 in `rest-proxy` and `runtime-adapter` components of ModelMesh.
Specifying python38 to keep sync between repos.
Working builds.
> fix: Specify and link python38

- .github/workflows/build.yml
- .github/workflows/fvt-base.yml
- .github/workflows/fvt-cs.yml
- .github/workflows/fvt-ns.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .gitignore
- config/default/config-defaults.yaml
- config/dependencies/fvt.yaml
- config/dependencies/quickstart.yaml
- config/manager/kustomization.yaml
- docs/component-versions.md
- docs/install/install-script.md
- docs/quickstart.md
- scripts/setup_user_namespaces.sh
Update image tags for `v0.11.2` following the [release process](https://github.com/kserve/modelmesh-serving/blob/main/docs/release-process.md#update-release-tags):
1. Create new (pre-)release tags (`v0.11.2`) in these repositories:
2. Verify image tags were pushed to [DockerHub](https://hub.docker.com/u/kserve):
3. In this `modelmesh-serving` repository, on the `release-0.11.2` branch, update the
container image tags to the corresponding release versions in the following files:
`Installation` section to the new `release-*` branch name and remove the
note pointing to the (old) `release-*` branch
_"Clone the ModelMesh repository"_ section to the new `release-*` branch
and remove the note of caution in the introduction above
4. [x] Submit your PR to the `release-*` branch that was created …
> release: Update `v0.11.2` image tags

- .gitignore
- docs/component-versions.md
- docs/install/install-script.md
- docs/quickstart.md
- docs/release-process.md
- scripts/setup_user_namespaces.sh
Doc updates post `v0.11.2` release as instructed in the [release process](https://github.com/kserve/modelmesh-serving/blob/main/docs/release-process.md#update-release-tags):
5. Update the following files in the `main` branch, replacing all occurrences
pointing to the old `release-*` branch or the previous release version tag
(e.g. `v0.11.2`) with the new release branch name or new version tags.
Submit them in a PR to `main`, and wait for that PR to be merged:
Docs will be current
> docs: Updates post release v0.11.2

- controllers/config/templating.go
If template parsing fails, the "foo" string would appear in pod logs. This should be very hard to happen, since the template is built-in. Changing, simply, to have more meaningful logs.
Fixes opendatahub-io/modelmesh-serving#114
> Replace "foo" string with a less generic one

- go.mod
- go.sum
Fix https://security.snyk.io/vuln/SNYK-GOLANG-GOOGLEGOLANGORGPROTOBUFENCODINGPROTOJSON-6137908
> chore: Update protobuf to v1.32.0

- docs/install/install-script.md
- docs/quickstart.md
Followed the quickstart and ran into "jq not found" when running the following command. [Quickstart link](https://github.com/kserve/modelmesh-serving/blob/91b610bd1bcd8d5264dcd696db4e2b65730f7468/scripts/self-signed-ca.sh#L136-L139)
```./scripts/install.sh --namespace modelmesh-serving --quickstart --enable-self-signed-ca```
The following change made jq a necessary dependency:
https://github.com/kserve/modelmesh-serving/blob/91b610bd1bcd8d5264dcd696db4e2b65730f7468/scripts/self-signed-ca.sh#L136-L139
Modified the list under the following link to point to where jq can be downloaded or installed https://github.com/kserve/modelmesh-serving/blob/main/docs/quickstart.md#prerequisites
The prerequisites list has the link detailed below.
> docs: Include the required jq dependency

- .github/workflows/fvt-base.yml
- config/default/config-defaults.yaml
- config/dependencies/fvt.yaml
- config/dependencies/quickstart.yaml
- config/manager/kustomization.yaml
- docs/component-versions.md
- docs/install/install-script.md
- docs/quickstart.md
- scripts/setup_user_namespaces.sh
Preparation for `v0.12.0-rc0` release.
Version references updated in the following files:
> release: Update v0.12.0-rc0 version references

- controllers/modelmesh/runtime.go
- controllers/testdata/servingruntime_controller.golden
Added s390x in node affinity rule as already work is going on to support s390x for tensorflow in runtime-adaptor
> feat: add S390x support in affinity rule

- config/default/storage-secret.yaml
- config/dependencies/fvt.yaml
- config/dependencies/minio-storage-secret.yaml
- config/dependencies/quickstart.yaml
- docs/predictors/README.md
- docs/predictors/setup-storage.md
- fvt/globals.go
Replacing default_bucket -> bucket everywhere in this repo to ensure it's consistent with KServe.
replaced every instance of `default_bucket` to `bucket`
Tested the [quickstart install](https://github.com/kserve/modelmesh-serving/blob/main/docs/quickstart.md) after modifying [quickstart.yaml](https://github.com/kserve/modelmesh-serving/blob/6c86da9473d50de63f9ea3af8a4d7c223849547e/config/dependencies/quickstart.yaml#L127) 
pods up and running - 
```
kubectl get pods
NAME                                              READY   STATUS    RESTARTS   AGE
etcd-6fdc487479-m9pkx                             1/1     Running   0          32m
minio-6b5c846587-8bwdv                            1/1     Running   0          32m
modelmesh-controller-5cd8d68bc-9ls9p              1/1     Running   0 …
```
> docs: changed every instance of default_bucket to bucket

- Dockerfile.develop
chore:	The ubi8/go-toolset:1.21 was released, we can now revert the develop image
to this image.
> Use ubi8 go-toolset:1.21

- controllers/modelmesh/modelmesh.go
- controllers/modelmesh/proxy.go
- controllers/testdata/servingruntime_controller.golden
- pkg/config/config.go
rest-proxy has a new environment variable for allowing the user to skip verification when using TLS
Adding the variable to the RESTProxyConfig and to the Deployments
Users will be able to specify if they want to skip verification when using TLS
See: [RHOAIENG-14237](https://issues.redhat.com/browse/RHOAIENG-14237)
> [RHOAIENG-14237] Adding REST_PROXY_SKIP_VERIFY env var.
